// 24 journal page faces. Sheet i shows pages[2i] on its front (right side
// when unflipped) and pages[2i+1] on its back (left side once flipped).
const journalPages = [
  {
    title: "Sofia's Journal",
    body: [
      '',
      'welcome to my room.',
      '',
      'flip through if you want',
      'to know me a little better.',
    ],
    doodle: 'star',
    center: true,
  },
  {
    title: 'about me',
    body: [
      "Hi, I'm Sofia. I occasionally",
      'volunteer for conferences and',
      'participate in CTFs.',
      '',
      'I love video games, and so',
      "'Life is Strange' is the main",
      'inspiration behind this page.',
      '',
      'I am very proud of this world,',
      'so if you catch any bugs or',
      'have suggestions let me know (:',
    ],
    doodle: 'heart',
  },
  {
    title: 'right now',
    body: [
      'I am currently studying for',
      'the CPTS by Hack The Box,',
      'working in an IT department',
      'and doing a fellowship at',
      'Hacker Sidekick!',
      '',
      'I am actively seeking an',
      'entry level role in',
      'cybersecurity.',
    ],
  },
  {
    title: 'school',
    body: [
      'Elmhurst University',
      'BS Computer Science,',
      'minor in Spanish',
      '2022 - 2026',
      '',
      'EdX & Columbia University',
      'Cybersecurity Bootcamp, 2024',
    ],
  },
  {
    title: 'certs',
    body: [
      'CompTIA Security+',
      '',
      'Cybersecurity Bootcamp',
      'certificate',
      '',
      'CPTS (loading...)',
      '',
      'more coming soon...',
      'probably. hopefully.',
    ],
    doodle: 'check',
  },
  {
    title: 'IT support days',
    body: [
      'Elmhurst University,',
      '2025 - present.',
      '',
      'Kept 200+ classroom devices',
      'alive and 800+ people calm.',
      '',
      'I love problem solving, and',
      'working in IT has taught',
      'me so much!',
    ],
  },
  {
    title: 'this website',
    body: [
      'The room you are sitting in.',
      'Three.js, React, Blender.',
      '',
      "One day, sitting by my room's",
      'door looking over my desk, I',
      'realised how much I love it -',
      'I kind of built it myself -',
      'so it ought to be my portfolio:',
      'a way to capture this place',
      'and share it with you.',
      '',
      "And like I said before, 'Life",
      "is Strange' is my inspiration.",
    ],
  },
  {
    title: 'The Well',
    body: [
      'A habit-tracking app I built',
      'for 17+ research participants.',
      '',
      '.NET MAUI, ASP.NET Core,',
      'PostgreSQL, JWT, AES-256.',
      '',
      'Hardened against brute force',
      'because I would try it too.',
    ],
  },
  {
    title: 'security toolbox',
    body: [
      'Nessus / Tenable',
      'Wireshark',
      'Nmap',
      'Burpsuite',
      '',
      'I am also an amateur',
      'lockpicker and I dabble',
      'in soldering (:',
    ],
  },
  {
    title: 'conferences 2025',
    body: [
      'THOTCON . BSides 312',
      'Hak4Kidz . BlueTeamCon',
      'GrrCON . BSides Chicago',
      'GCSI',
      '',
      'mostly volunteering,',
      'always at the badge table.',
    ],
  },
  {
    title: 'conferences 2026',
    body: [
      'ChiBrrCon . BSides Seattle',
      'WiCyS . CypherCon . GCSI',
      'BSides 312 . BSides Detroit',
      'SecretCon . Hak4Kidz',
      '',
      'next up: Black Hat and',
      'DEF CON. finally.',
    ],
    doodle: 'star',
  },
  {
    title: 'CTFs',
    body: [
      'NCL Spring 2026',
      'Tenable x WiCyS CTF',
      'UIC Capture The Flame',
    ],
    doodle: 'flag',
  },
  {
    title: 'say hi',
    body: [
      'sofia@sofiabatala.com',
      '',
      'linkedin.com/in/batalasofia',
      '',
      'github.com/bscsaki',
      '',
      'the laptop on my desk has',
      'the full resume.',
    ],
    doodle: 'heart',
  },
  {
    title: 'thank you',
    body: [
      'for flipping all the way',
      'to the end.',
    ],
    center: true,
  },
  {
    title: 'the end',
    body: [
      '',
      '',
      '( for now )',
    ],
    doodle: 'star',
    center: true,
  },
  ...Array.from({ length: 9 }, () => ({
    title: '',
    body: ['', '', '', '', 'loading...'],
    center: true,
  })),
]

export default journalPages
