/*
Base scene auto-generated by gltfjsx from public/models/2books.glb,
extended with: journal page flipping, cover-bone animation, day/night sky
videos, window sun shafts, dust motes and shooting stars.
*/

import React, { Suspense, useEffect, useLayoutEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture, useVideoTexture } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import useStore from '../store/useStore'
import useJournalTextures from './journalTextures'

const PAGE_COUNT = 12
const PAGE_BASE_POS = [0.113, 0.069, 0.006]
const PAGE_BASE_ROT = [-Math.PI, 1.199, Math.PI / 2]
const PAGE_BASE_SCALE = 0.276
const Q_COVER_CLOSED = new THREE.Quaternion(0, 0, 0.7071, 0.7071)
const Q_COVER_OPEN = new THREE.Quaternion(0, 0, 0, 1)
const easeInOut = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2)

function SkyBackdrop() {
  const dayMode = useStore((s) => s.dayMode)
  const texture = useVideoTexture(dayMode ? '/videos/day-sky.mp4' : '/videos/night-sky.mp4', {
    muted: true,
    loop: true,
    start: true,
  })
  texture.colorSpace = THREE.SRGBColorSpace
  useEffect(() => {
    if (texture.image) texture.image.playbackRate = 0.55
  }, [texture])
  return (
    <mesh position={[1.707, 1.6, -1.6]}>
      <planeGeometry args={[4, 5.4]} />
      <meshBasicMaterial map={texture} toneMapped={false} />
    </mesh>
  )
}

function makeShaftTexture() {
  const c = document.createElement('canvas')
  c.width = 64
  c.height = 256
  const ctx = c.getContext('2d')
  const g = ctx.createLinearGradient(0, 0, 0, 256)
  g.addColorStop(0, 'rgba(255,214,150,0.9)')
  g.addColorStop(0.55, 'rgba(255,214,150,0.35)')
  g.addColorStop(1, 'rgba(255,214,150,0)')
  ctx.fillStyle = g
  ctx.fillRect(0, 0, 64, 256)
  // soften the sides
  const gx = ctx.createLinearGradient(0, 0, 64, 0)
  gx.addColorStop(0, 'rgba(0,0,0,1)')
  gx.addColorStop(0.25, 'rgba(0,0,0,0)')
  gx.addColorStop(0.75, 'rgba(0,0,0,0)')
  gx.addColorStop(1, 'rgba(0,0,0,1)')
  ctx.globalCompositeOperation = 'destination-out'
  ctx.fillStyle = gx
  ctx.fillRect(0, 0, 64, 256)
  const tex = new THREE.CanvasTexture(c)
  tex.colorSpace = THREE.SRGBColorSpace
  return tex
}

function SunShaft({ position, rotation }) {
  const groupRef = useRef()
  const tex = useMemo(makeShaftTexture, [])
  const mats = useRef([])
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime()
    mats.current.forEach((m, i) => {
      if (m) m.opacity = m.userData.base * (0.85 + 0.15 * Math.sin(t * 0.6 + i * 1.7))
    })
  })
  const layers = [
    { w: 0.85, o: 0.28, roll: 0 },
    { w: 0.6, o: 0.18, roll: 0.5 },
    { w: 1.05, o: 0.1, roll: -0.45 },
  ]
  return (
    <group ref={groupRef} position={position} rotation={rotation}>
      {layers.map((l, i) => (
        <mesh key={i} rotation={[0, l.roll, 0]} position={[0, -1.25, 0]}>
          <planeGeometry args={[l.w, 2.5]} />
          <meshBasicMaterial
            ref={(m) => {
              if (m) {
                m.userData.base = l.o
                mats.current[i] = m
              }
            }}
            map={tex}
            transparent
            opacity={l.o}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            side={THREE.DoubleSide}
            toneMapped={false}
          />
        </mesh>
      ))}
    </group>
  )
}

function DustMotes() {
  const ref = useRef()
  const count = 60
  const seeds = useMemo(() => {
    const arr = []
    for (let i = 0; i < count; i++) {
      arr.push({
        x: 0.5 + Math.random() * 2.6,
        y: 0.4 + Math.random() * 1.9,
        z: -1.2 + Math.random() * 1.5,
        s: 0.15 + Math.random() * 0.35,
        p: Math.random() * Math.PI * 2,
      })
    }
    return arr
  }, [])
  const positions = useMemo(() => new Float32Array(count * 3), [])
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime()
    for (let i = 0; i < count; i++) {
      const s = seeds[i]
      positions[i * 3] = s.x + Math.sin(t * 0.12 * s.s + s.p) * 0.14
      positions[i * 3 + 1] = s.y + Math.sin(t * 0.09 * s.s + s.p * 2) * 0.18 - ((t * 0.01 * s.s + s.p) % 0.3)
      positions[i * 3 + 2] = s.z + Math.cos(t * 0.1 * s.s + s.p) * 0.1
    }
    if (ref.current) ref.current.geometry.attributes.position.needsUpdate = true
  })
  return (
    <points ref={ref}>
      <bufferGeometry>
        <bufferAttribute attach="attributes-position" count={count} array={positions} itemSize={3} />
      </bufferGeometry>
      <pointsMaterial
        color="#ffe1b0"
        size={0.008}
        transparent
        opacity={0.5}
        blending={THREE.AdditiveBlending}
        depthWrite={false}
        sizeAttenuation
      />
    </points>
  )
}

function makeStreakTexture() {
  const c = document.createElement('canvas')
  c.width = 256
  c.height = 32
  const ctx = c.getContext('2d')
  const g = ctx.createLinearGradient(0, 0, 256, 0)
  g.addColorStop(0, 'rgba(255,255,255,0)')
  g.addColorStop(0.75, 'rgba(230,240,255,0.55)')
  g.addColorStop(0.95, 'rgba(255,255,255,1)')
  g.addColorStop(1, 'rgba(255,255,255,0)')
  ctx.fillStyle = g
  ctx.fillRect(0, 0, 256, 32)
  const gy = ctx.createLinearGradient(0, 0, 0, 32)
  gy.addColorStop(0, 'rgba(0,0,0,1)')
  gy.addColorStop(0.5, 'rgba(0,0,0,0)')
  gy.addColorStop(1, 'rgba(0,0,0,1)')
  ctx.globalCompositeOperation = 'destination-out'
  ctx.fillStyle = gy
  ctx.fillRect(0, 0, 256, 32)
  const tex = new THREE.CanvasTexture(c)
  tex.colorSpace = THREE.SRGBColorSpace
  return tex
}

function ShootingStars() {
  const SLOTS = 3
  const tex = useMemo(makeStreakTexture, [])
  const meshRefs = useRef([])
  const stars = useRef(
    Array.from({ length: SLOTS }, (_, i) => ({
      delay: 1.5 + i * 2.5 + Math.random() * 3,
      life: 0,
      maxLife: 1,
      x: 0,
      y: 0,
      vx: 0,
      vy: 0,
    }))
  )

  const respawn = (s) => {
    s.delay = 2 + Math.random() * 5
    s.maxLife = 0.7 + Math.random() * 0.6
    s.life = s.maxLife
    const leftToRight = Math.random() > 0.5
    s.x = leftToRight ? 0.1 + Math.random() * 1.2 : 2.2 + Math.random() * 1.2
    s.y = 2.4 + Math.random() * 1.6
    const speed = 1.6 + Math.random() * 1.2
    s.vx = (leftToRight ? 1 : -1) * speed
    s.vy = -speed * (0.35 + Math.random() * 0.25)
  }

  useFrame((_, dt) => {
    stars.current.forEach((s, i) => {
      const mesh = meshRefs.current[i]
      if (!mesh) return
      if (s.delay > 0) {
        s.delay -= dt
        mesh.visible = false
        if (s.delay <= 0) {
          // becomes active with pre-set trajectory
        }
        return
      }
      if (s.life === s.maxLife && s.vx === 0) respawn(s)
      s.life -= dt
      if (s.life <= 0) {
        respawn(s)
        mesh.visible = false
        return
      }
      s.x += s.vx * dt
      s.y += s.vy * dt
      mesh.visible = true
      mesh.position.set(s.x, s.y, -1.57)
      mesh.rotation.z = Math.atan2(s.vy, s.vx) + (s.vx < 0 ? Math.PI : 0)
      const fade = Math.sin(Math.PI * (s.life / s.maxLife))
      mesh.material.opacity = fade * 0.9
    })
  })

  useEffect(() => {
    stars.current.forEach((s) => {
      s.vx = 0
      s.life = s.maxLife
    })
  }, [])

  return (
    <>
      {Array.from({ length: SLOTS }, (_, i) => (
        <mesh key={i} ref={(el) => (meshRefs.current[i] = el)} visible={false}>
          <planeGeometry args={[0.5, 0.02]} />
          <meshBasicMaterial
            map={tex}
            transparent
            opacity={0}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            toneMapped={false}
          />
        </mesh>
      ))}
    </>
  )
}

export function Model(props) {
  const group = React.useRef()
  window.__dbg = window.__dbg || []
  window.__dbg.push('model-enter')
  const { scene, animations } = useGLTF('/models/2books.glb')
  window.__dbg.push('gltf-ready')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  window.__nodes = nodes
  const { actions } = useAnimations(animations, group)
  window.__dbg.push('pre-textures')
  const wallpaperTexture = useTexture('/textures/Bliss.png')
  window.__dbg.push('textures-ready')
  wallpaperTexture.flipY = false
  wallpaperTexture.colorSpace = THREE.SRGBColorSpace

  const aboutPhotoTexture = useTexture('/images/about.jpg')
  aboutPhotoTexture.flipY = false
  aboutPhotoTexture.colorSpace = THREE.SRGBColorSpace

  const journalTextures = useJournalTextures()

  const setSceneReady = useStore((s) => s.setSceneReady)
  useEffect(() => {
    if (journalTextures) setSceneReady()
  }, [journalTextures, setSceneReady])

  const setHovered = useStore((s) => s.setHovered)
  const setView = useStore((s) => s.setView)
  const viewState = useStore((s) => s.viewState)
  const pageIndex = useStore((s) => s.pageIndex)
  const lampOn = useStore((s) => s.lampOn)
  const toggleLamp = useStore((s) => s.toggleLamp)
  const dayMode = useStore((s) => s.dayMode)

  // ---- Laptop open/close (baked clip) ----
  const hasMounted = useRef(false)
  useLayoutEffect(() => {
    const a = actions['PARENTAction']
    if (!a) return
    a.setLoop(THREE.LoopOnce)
    a.clampWhenFinished = true
    a.paused = false

    if (!hasMounted.current) {
      hasMounted.current = true
      a.play()
      a.time = viewState === 'laptop' ? 0 : a.getClip().duration
      a.paused = true
    } else {
      a.timeScale = viewState === 'laptop' ? -1.5 : 1.5
      a.play()
    }

    // Keep every other baked action off; pages + cover are driven manually.
    Object.entries(actions).forEach(([name, action]) => {
      if (name !== 'PARENTAction') {
        action.stop()
        action.enabled = false
        action.weight = 0
      }
    })
  }, [viewState, actions])

  // ---- Journal cover bones ----
  const coverBones = useMemo(() => {
    const sk = nodes.Cube002?.skeleton
    if (!sk) return []
    // bone names may carry dedup suffixes (e.g. Bone001_1) from the second armature
    return sk.bones.filter((b) => /00[12]/.test(b.name))
  }, [nodes])
  const coverT = useRef(0)

  // ---- Page flip state ----
  const flipRefs = useRef([])
  const flipAngles = useRef(new Array(PAGE_COUNT).fill(0))
  const liftRefs = useRef([])

  const pageGeometries = useMemo(() => {
    const geos = []
    for (let i = 0; i < PAGE_COUNT; i++) {
      const n = nodes[`Page_${i * 2 + 1}-${i * 2 + 2}`]
      geos.push(n ? n.geometry : null)
    }
    return geos
  }, [nodes])

  const pageMaterials = useMemo(() => {
    if (!journalTextures) return null
    const mats = []
    for (let i = 0; i < PAGE_COUNT; i++) {
      // low emissive keeps the handwriting readable in night mode
      const front = new THREE.MeshStandardMaterial({
        map: journalTextures[i * 2],
        roughness: 0.92,
        side: THREE.FrontSide,
        emissive: '#ffffff',
        emissiveMap: journalTextures[i * 2],
        emissiveIntensity: 0.22,
      })
      const back = new THREE.MeshStandardMaterial({
        map: journalTextures[i * 2 + 1],
        roughness: 0.92,
        side: THREE.BackSide,
        emissive: '#ffffff',
        emissiveMap: journalTextures[i * 2 + 1],
        emissiveIntensity: 0.22,
      })
      mats.push([front, back])
    }
    return mats
  }, [journalTextures])

  useFrame((_, dt) => {
    const d = Math.min(dt, 0.05)
    // cover open/close
    const coverTarget = viewState === 'notebook' ? 1 : 0
    coverT.current += (coverTarget - coverT.current) * Math.min(1, d * 4.5)
    const e = easeInOut(THREE.MathUtils.clamp(coverT.current, 0, 1))
    coverBones.forEach((b) => {
      b.quaternion.slerpQuaternions(Q_COVER_CLOSED, Q_COVER_OPEN, e)
    })
    // pages follow only once the cover is mostly open (and close before the cover does)
    const pagesUnlocked = coverT.current > 0.55 || viewState !== 'notebook'
    for (let i = 0; i < PAGE_COUNT; i++) {
      const flipped = viewState === 'notebook' && pageIndex > i && pagesUnlocked
      // negative Y: travel up and over the spine. Rest well short of PI so the
      // sheet sits propped above the open cover (which bows upward near the
      // spine) instead of intersecting it. Later sheets rest shallower so they
      // stack on top of earlier ones.
      const target = flipped ? -(Math.PI - 0.13 - 0.009 * i) : -0.0015 * i
      const cur = flipAngles.current[i]
      const next = cur + (target - cur) * Math.min(1, d * 5.5)
      flipAngles.current[i] = next
      const g = flipRefs.current[i]
      if (g) g.rotation.y = next
      // arc lift while in flight, plus a firm rest lift so flipped sheets sit
      // visibly above the cover and hide the spine strip from the camera
      const outer = liftRefs.current[i]
      if (outer) {
        const p = Math.min(1, Math.abs(next) / Math.PI)
        outer.position.y = PAGE_BASE_POS[1] + Math.sin(p * Math.PI) * 0.016 + p * 0.022
      }
    }
  })

  // ---- Journal page brightness: realistic in the dark, still readable ----
  useEffect(() => {
    if (!pageMaterials) return
    const intensity = dayMode ? 0.22 : lampOn ? 0.1 : 0.055
    const tint = dayMode ? '#ffffff' : lampOn ? '#ffe9c4' : '#cfd6e4'
    pageMaterials.forEach(([front, back]) => {
      front.emissiveIntensity = intensity
      back.emissiveIntensity = intensity
      front.emissive.set(tint)
      back.emissive.set(tint)
    })
  }, [pageMaterials, dayMode, lampOn])

  // ---- Lamp shade glow ----
  useEffect(() => {
    const shade = materials['24 - Default']
    if (shade) {
      shade.emissive = new THREE.Color('#ffd98a')
      shade.emissiveIntensity = lampOn ? 0.85 : 0
      shade.needsUpdate = true
    }
  }, [lampOn, materials])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* LAPTOP */}
        <group
          name="PARENT"
          position={[1.603, 0.056, -0.202]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={0.21}
          onPointerOver={() => setHovered('laptop')}
          onPointerOut={() => setHovered(null)}
          onClick={() => {
            if (viewState !== 'laptop') setView('laptop')
          }}
        >
          <group name="Plane001_1" position={[-0.118, 0.062, -2.807]} rotation={[0, 0, 1.923]} scale={[2, 2, 2.914]}>
            <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials['color.003']} />
            <mesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials['screen border.001']} />
            <mesh
              name="Plane001_5"
              geometry={nodes.Plane001_5.geometry}
              material={materials['wallpeper.001']}
              material-toneMapped={false}
              material-emissive="#ffffff"
              material-emissiveMap={materials['wallpeper.001'].map}
              material-emissiveIntensity={1}
            />
            <mesh name="Plane001_6" geometry={nodes.Plane001_6.geometry} material={materials['webcam.001']} />
          </group>
        </group>

        {/* JOURNAL (interactive book) */}
        <group
          name="BookGroup"
          onPointerOver={() => setHovered('notebook')}
          onPointerOut={() => setHovered(null)}
          onClick={(e) => {
            e.stopPropagation()
            if (viewState !== 'notebook') setView('notebook')
          }}
        >
          <group name="Armature" position={[0.131, 0.066, 0]} rotation={[Math.PI, -0.371, Math.PI / 2]} scale={0.276}>
            <primitive object={nodes.Bone_1} />
            <group name="Cover">
              <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.cover} skeleton={nodes.Cube002.skeleton} />
              <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['cover interior']} skeleton={nodes.Cube002_1.skeleton} />
              <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['cover border']} skeleton={nodes.Cube002_2.skeleton} />
            </group>
          </group>
          <group name="couverture001" position={[0.118, 0.066, 0.004]} rotation={[Math.PI / 2, 0, 2.77]} scale={0.276}>
            <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials.cover} />
            <mesh name="Plane032_1" geometry={nodes.Plane032_1.geometry} material={materials.Rim} />
            <mesh name="Plane032_2" geometry={nodes.Plane032_2.geometry} material={materials['couv interieur']} />
          </group>

          {/* Flippable sheets: base transform on outer group, flip on inner group (local Y = spine) */}
          {pageGeometries.map((geo, i) =>
            geo ? (
              <group
                key={i}
                position={PAGE_BASE_POS}
                rotation={PAGE_BASE_ROT}
                scale={PAGE_BASE_SCALE}
                ref={(el) => (liftRefs.current[i] = el)}
              >
                <group ref={(el) => (flipRefs.current[i] = el)}>
                  {pageMaterials ? (
                    <>
                      <mesh geometry={geo} material={pageMaterials[i][0]} />
                      <mesh geometry={geo} material={pageMaterials[i][1]} />
                    </>
                  ) : (
                    <mesh geometry={geo} material={materials[`page ${i * 2 + 1}-${i * 2 + 2}`]} />
                  )}
                </group>
              </group>
            ) : null
          )}
          <mesh name="fond_livre" geometry={nodes.fond_livre.geometry} material={materials.tranche} position={[0.113, 0.067, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={[0.276, 0.276, 0.209]} />
        </group>

        {/* zero yaw so the desk front edge projects perfectly level from the
            straight-on overview camera */}
        <mesh name="Foot" geometry={nodes.Foot.geometry} material={materials.MetalBlack} position={[1.701, -1.888, -0.463]} rotation={[0, 0, 0]} scale={[1.802, 1.802, 1.803]} />
        <mesh name="Top" geometry={nodes.Top.geometry} material={materials.MetalBlack} position={[1.701, -1.294, -0.463]} rotation={[0, 0, 0]} scale={[1.802, 1.802, 1.803]} />
        <mesh name="Desk" geometry={nodes.Desk.geometry} material={materials['WoodQuarteredChiffon001_4K.002']} position={[1.699, 0.038, -0.055]} rotation={[0, 0, 0]} scale={[2.011, 2.011, 1.881]} />
        {/* Little sculpture */}
        <mesh
          name="model-meshmixer-metashape"
          geometry={nodes['model-meshmixer-metashape'].geometry}
          material={materials['model-meshmixer-metashape']}
          position={[0.22, 0.264, -1.185]}
          rotation={[2.978, 0.26, -2.067]}
          scale={0.495}
          onPointerOver={() => setHovered('head')}
          onPointerOut={() => setHovered(null)}
        />
        {/* Trojan horse */}
        <mesh
          name="antikensammlung-pferd-model-meshmixer-metashape"
          geometry={nodes['antikensammlung-pferd-model-meshmixer-metashape'].geometry}
          material={materials['WoodQuarteredChiffon001_4K.002']}
          position={[1.127, 0.355, -1.134]}
          rotation={[0.123, 0.242, 1.068]}
          scale={0.422}
          onPointerOver={() => setHovered('horse')}
          onPointerOut={() => setHovered(null)}
        />

        {/* PICTURE FRAME */}
        <group
          name="PictureFrame001"
          position={[3.345, 0.357, 0.036]}
          rotation={[-Math.PI, -1.108, -2.799]}
          scale={0.316}
          onPointerOver={() => setHovered('frame')}
          onPointerOut={() => setHovered(null)}
          onClick={(e) => {
            e.stopPropagation()
            if (viewState !== 'frame') setView('frame')
          }}
        >
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.PictureFrame}
            material-map={aboutPhotoTexture}
          />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.FrameWhite} />
          <mesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.FrameBorder} />
          <mesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.FrameBack} />
        </group>

        <mesh name="Stand001" geometry={nodes.Stand001.geometry} material={materials.Stand} position={[3.442, 0.195, -0.035]} rotation={[2.096, -0.735, 0.023]} scale={0.144} />

        {/* WINDOWS */}
        <mesh
          name="window"
          geometry={nodes.window.geometry}
          material={nodes.window.material}
          position={[0.794, 2.134, -1.222]}
          rotation={[Math.PI / 2, 0, 1.574]}
          scale={[0.046, 0.046, 0.056]}
        />
        <mesh
          name="window001"
          geometry={nodes.window001.geometry}
          material={nodes.window001.material}
          position={[2.619, 2.129, -1.211]}
          rotation={[Math.PI / 2, 0, 1.574]}
          scale={[0.046, 0.046, 0.056]}
        />

        <Suspense fallback={null}>
          <SkyBackdrop />
        </Suspense>

        {/* Day: sunlight shafts + dust. Night: shooting stars. */}
        {dayMode && (
          <>
            <SunShaft position={[0.794, 2.05, -1.15]} rotation={[0.62, 0, -0.12]} />
            <SunShaft position={[2.619, 2.05, -1.14]} rotation={[0.62, 0, 0.1]} />
            <DustMotes />
          </>
        )}
        {!dayMode && <ShootingStars />}

        {/* LAMP */}
        <group
          name="LampGroup"
          onPointerOver={() => setHovered('lamp')}
          onPointerOut={() => setHovered(null)}
          onClick={(e) => {
            e.stopPropagation()
            toggleLamp()
          }}
        >
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['02 - Default']} position={[3.008, 0.072, -0.598]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={0.025} />
          <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials['14 - Default']} position={[2.999, 0.906, -0.597]} rotation={[0, 1.565, 0]} scale={0.025} />
          <group name="Line001" position={[3, 0.514, -0.597]} rotation={[Math.PI / 2, 0, -0.81]} scale={0.024}>
            <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['Mr-1']} />
            <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['Mr-2']} />
            <mesh name="Mesh004_2" geometry={nodes.Mesh004_2.geometry} material={materials['Mr-3']} />
            <mesh name="Mesh004_3" geometry={nodes.Mesh004_3.geometry} material={materials['Mr-4']} />
            <mesh name="Mesh004_4" geometry={nodes.Mesh004_4.geometry} material={materials['Mr-5']} />
          </group>
          <group name="Line035" position={[3, 0.921, -0.599]} rotation={[Math.PI / 2, 0, -3.136]} scale={0.023}>
            <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['23 - Default']} />
            <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['24 - Default']} />
          </group>
          <mesh name="Line017" geometry={nodes.Line017.geometry} material={materials['04 - Default']} position={[2.999, 1.121, -0.597]} rotation={[Math.PI / 2, 0, -3.136]} scale={0.024} />
          {lampOn && (
            <pointLight
              position={[2.999, 0.9, -0.597]}
              intensity={3}
              distance={0}
              decay={2}
              color="#ffd98a"
            />
          )}
          {lampOn && (
            /* faint spill onto the picture frame; the lamp sits behind it so
               only a whisper of warm light reaches the photo */
            <pointLight
              position={[3.05, 0.55, 0.55]}
              intensity={0.4}
              distance={1.4}
              decay={2}
              color="#ffd9a0"
            />
          )}
        </group>

        {/* KEYBOARD */}
        <group name="Plane" position={[1.707, 0.056, 0.193]} rotation={[Math.PI, -1.562, -3.139]} scale={[0.42, 0.42, 0.612]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['color.002']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['border.001']} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['keyboard.001']} />
          <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={materials['pad.001']} />
          <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={materials['dark.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/2books.glb')
