/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/2books.glb -o src/components/putall.jsx
*/

import React, { Suspense, useEffect, useLayoutEffect, useRef } from 'react'
import * as THREE from 'three'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture, useVideoTexture } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import useStore from '../store/useStore'

function CloudsBackdrop() {
  const dayMode = useStore((s) => s.dayMode)
  const texture = useVideoTexture(dayMode ? '/videos/clouds.mp4' : '/videos/nightsky.mp4', { muted: true, loop: true, start: true })
  useEffect(() => {
    if (texture.image) texture.image.playbackRate = 0.3
  }, [texture])
  return (
    <mesh position={[1.707, 1.6, -1.6]}>
      <planeGeometry args={[4, 5.4]} />
      <meshBasicMaterial map={texture} toneMapped={false} />
    </mesh>
  )
}

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/2books.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  const wallpaperTexture = useTexture('/textures/Bliss.png')
  wallpaperTexture.flipY = false
  wallpaperTexture.colorSpace = THREE.SRGBColorSpace

  const aboutPhotoTexture = useTexture('/images/about.jpg')
  aboutPhotoTexture.flipY = false
  aboutPhotoTexture.colorSpace = THREE.SRGBColorSpace

  const setHovered = useStore((s) => s.setHovered)
  const setView = useStore((s) => s.setView)
  const viewState = useStore((s) => s.viewState)
  const lampOn = useStore((s) => s.lampOn)
  const toggleLamp = useStore((s) => s.toggleLamp)
  const dayMode = useStore((s) => s.dayMode)

  // Laptop open/close
  const hasMounted = useRef(false)
  useLayoutEffect(() => {
    const a = actions['PARENTAction']
    if (!a) return
    a.setLoop(THREE.LoopOnce)
    a.clampWhenFinished = true
    a.paused = false

    if (!hasMounted.current) {
      // On first mount, snap instantly to the correct pose with no visible animation
      hasMounted.current = true
      a.play()
      a.time = viewState === 'laptop' ? 0 : a.getClip().duration
      a.paused = true
    } else {
      a.timeScale = viewState === 'laptop' ? -1.5 : 1.5
      a.play()
    }

    // Permanently disable every other action so nothing else can ever animate the book
    Object.entries(actions).forEach(([name, action]) => {
      if (name !== 'PARENTAction') {
        action.stop()
        action.enabled = false
        action.weight = 0
      }
    })
  }, [viewState, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* LAPTOP */}
        <group
          name="PARENT"
          position={[1.603, 0.056, -0.202]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={0.21}
          onPointerOver={() => setHovered('laptop')}
          onPointerOut={() => setHovered(null)}
          onClick={() => setView('laptop')}
        >
          <group name="Plane001_1" position={[-0.118, 0.062, -2.807]} rotation={[0, 0, 1.923]} scale={[2, 2, 2.914]}>
            <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials['color.003']} />
            <mesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials['screen border.001']} />
            <mesh
              name="Plane001_5"
              geometry={nodes.Plane001_5.geometry}
              material={materials['wallpeper.001']}
              material-toneMapped={false}
              material-emissive="#ffffff"
              material-emissiveMap={materials['wallpeper.001'].map}
              material-emissiveIntensity={1}
              ref={(el) => {
                if (el) {
                  window.logScreenCenter = () => {
                    const box = new THREE.Box3().setFromObject(el)
                    const center = box.getCenter(new THREE.Vector3())
                    const normalLocal = new THREE.Vector3(0, 0, 1)
                    const normalWorld = normalLocal.clone()
                    el.getWorldQuaternion(new THREE.Quaternion()).identity()
                    const q = new THREE.Quaternion()
                    el.getWorldQuaternion(q)
                    normalWorld.applyQuaternion(q).normalize()
                    console.log(`screen center: [${center.x.toFixed(3)}, ${center.y.toFixed(3)}, ${center.z.toFixed(3)}]`)
                    console.log(`screen normal: [${normalWorld.x.toFixed(4)}, ${normalWorld.y.toFixed(4)}, ${normalWorld.z.toFixed(4)}]`)
                    const dist = 0.7
                    const camPos = center.clone().add(normalWorld.clone().multiplyScalar(dist))
                    console.log(`suggested camera position (distance ${dist}): [${camPos.x.toFixed(3)}, ${camPos.y.toFixed(3)}, ${camPos.z.toFixed(3)}]`)
                  }
                }
              }}
            />
            <mesh name="Plane001_6" geometry={nodes.Plane001_6.geometry} material={materials['webcam.001']} />
          </group>
        </group>

        {/* BOOK - static for now, animation coming post-launch */}
        <group
          name="BookGroup"
          onPointerOver={() => setHovered('notebook')}
          onPointerOut={() => setHovered(null)}
        >
          <group name="Armature" position={[0.131, 0.066, 0]} rotation={[Math.PI, -0.371, Math.PI / 2]} scale={0.276}>
            <primitive object={nodes.Bone_1} />
            <group name="Cover">
              <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.cover} skeleton={nodes.Cube002.skeleton} />
              <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['cover interior']} skeleton={nodes.Cube002_1.skeleton} />
              <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['cover border']} skeleton={nodes.Cube002_2.skeleton} />
            </group>
          </group>
          <group name="couverture001" position={[0.118, 0.066, 0.004]} rotation={[Math.PI / 2, 0, 2.77]} scale={0.276}>
            <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials.cover} />
            <mesh name="Plane032_1" geometry={nodes.Plane032_1.geometry} material={materials.Rim} />
            <mesh name="Plane032_2" geometry={nodes.Plane032_2.geometry} material={materials['couv interieur']} />
          </group>
          <mesh name="Page_1-2" geometry={nodes['Page_1-2'].geometry} material={materials['page 1-2']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_3-4" geometry={nodes['Page_3-4'].geometry} material={materials['page 3-4']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_5-6" geometry={nodes['Page_5-6'].geometry} material={materials['page 5-6']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_7-8" geometry={nodes['Page_7-8'].geometry} material={materials['page 7-8']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_9-10" geometry={nodes['Page_9-10'].geometry} material={materials['page 9-10']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_11-12" geometry={nodes['Page_11-12'].geometry} material={materials['page 11-12']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_13-14" geometry={nodes['Page_13-14'].geometry} material={materials['page 13-14']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_15-16" geometry={nodes['Page_15-16'].geometry} material={materials['page 15-16']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_17-18" geometry={nodes['Page_17-18'].geometry} material={materials['page 17-18']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_19-20" geometry={nodes['Page_19-20'].geometry} material={materials['page 19-20']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_21-22" geometry={nodes['Page_21-22'].geometry} material={materials['page 21-22']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="Page_23-24" geometry={nodes['Page_23-24'].geometry} material={materials['page 23-24']} position={[0.113, 0.069, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={0.276} />
          <mesh name="fond_livre" geometry={nodes.fond_livre.geometry} material={materials.tranche} position={[0.113, 0.067, 0.006]} rotation={[-Math.PI, 1.199, Math.PI / 2]} scale={[0.276, 0.276, 0.209]} />
        </group>

        <mesh name="Foot" geometry={nodes.Foot.geometry} material={materials.MetalBlack} position={[1.701, -1.888, -0.463]} rotation={[0, -0.005, 0]} scale={[1.802, 1.802, 1.803]} />
        <mesh name="Top" geometry={nodes.Top.geometry} material={materials.MetalBlack} position={[1.701, -1.294, -0.463]} rotation={[0, -0.005, 0]} scale={[1.802, 1.802, 1.803]} />
        <mesh name="Desk" geometry={nodes.Desk.geometry} material={materials['WoodQuarteredChiffon001_4K.002']} position={[1.699, 0.038, -0.055]} rotation={[0, -0.005, 0]} scale={[2.011, 2.011, 1.881]} />
        <mesh name="model-meshmixer-metashape" geometry={nodes['model-meshmixer-metashape'].geometry} material={materials['model-meshmixer-metashape']} position={[0.22, 0.264, -1.185]} rotation={[2.978, 0.26, -2.067]} scale={0.495} />
        <mesh name="antikensammlung-pferd-model-meshmixer-metashape" geometry={nodes['antikensammlung-pferd-model-meshmixer-metashape'].geometry} material={materials['WoodQuarteredChiffon001_4K.002']} position={[1.127, 0.355, -1.134]} rotation={[0.123, 0.242, 1.068]} scale={0.422} />

        {/* PICTURE FRAME */}
        <group
          name="PictureFrame001"
          position={[3.345, 0.357, 0.036]}
          rotation={[-Math.PI, -1.108, -2.799]}
          scale={0.316}
          onPointerOver={() => setHovered('frame')}
          onPointerOut={() => setHovered(null)}
          onClick={(e) => { e.stopPropagation(); setView('frame') }}
        >
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.PictureFrame}
            material-map={aboutPhotoTexture}
          />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.FrameWhite} />
          <mesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.FrameBorder} />
          <mesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.FrameBack} />
        </group>

        <mesh name="Stand001" geometry={nodes.Stand001.geometry} material={materials.Stand} position={[3.442, 0.195, -0.035]} rotation={[2.096, -0.735, 0.023]} scale={0.144} />
        <mesh
          name="window"
          geometry={nodes.window.geometry}
          material={nodes.window.material}
          position={[0.794, 2.134, -1.222]}
          rotation={[Math.PI / 2, 0, 1.574]}
          scale={[0.046, 0.046, 0.056]}
        />
        <mesh
          name="window001"
          geometry={nodes.window001.geometry}
          material={nodes.window001.material}
          position={[2.619, 2.129, -1.211]}
          rotation={[Math.PI / 2, 0, 1.574]}
          scale={[0.046, 0.046, 0.056]}
        />
        <Suspense fallback={null}>
          <CloudsBackdrop />
        </Suspense>

        {/* LAMP */}
        <group
          name="LampGroup"
          onPointerOver={() => setHovered('lamp')}
          onPointerOut={() => setHovered(null)}
          onClick={(e) => { e.stopPropagation(); toggleLamp() }}
        >
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['02 - Default']} position={[3.008, 0.072, -0.598]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={0.025} />
          <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials['14 - Default']} position={[2.999, 0.906, -0.597]} rotation={[0, 1.565, 0]} scale={0.025} />
          <group name="Line001" position={[3, 0.514, -0.597]} rotation={[Math.PI / 2, 0, -0.81]} scale={0.024}>
            <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['Mr-1']} />
            <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['Mr-2']} />
            <mesh name="Mesh004_2" geometry={nodes.Mesh004_2.geometry} material={materials['Mr-3']} />
            <mesh name="Mesh004_3" geometry={nodes.Mesh004_3.geometry} material={materials['Mr-4']} />
            <mesh name="Mesh004_4" geometry={nodes.Mesh004_4.geometry} material={materials['Mr-5']} />
          </group>
          <group name="Line035" position={[3, 0.921, -0.599]} rotation={[Math.PI / 2, 0, -3.136]} scale={0.023}>
            <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['23 - Default']} />
            <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['24 - Default']} />
          </group>
          <mesh name="Line017" geometry={nodes.Line017.geometry} material={materials['04 - Default']} position={[2.999, 1.121, -0.597]} rotation={[Math.PI / 2, 0, -3.136]} scale={0.024} />
          {lampOn && (
            <pointLight
              position={[2.999, 0.9, -0.597]}
              intensity={3}
              distance={0}
              decay={2}
              color="#ffd98a"
            />
          )}
        </group>

        <group name="Plane" position={[1.707, 0.056, 0.193]} rotation={[Math.PI, -1.562, -3.139]} scale={[0.42, 0.42, 0.612]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['color.002']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['border.001']} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['keyboard.001']} />
          <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={materials['pad.001']} />
          <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={materials['dark.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/2books.glb')
